version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ramzi
      POSTGRES_DB: users_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-sp
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ramzi
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front-ng
    ports:
      - '4200:4200'
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  db-data:
  node_modules:

networks:
  app-network:
    driver: bridge
